{
 "title": "Apple Health Specific Metrics",
 "time": { "from": "2022-12-01T05:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "show tag values from StepCount with key=device"
   },
   { "name": "period", "query": "1d,1w,2w,30d,90d,180d,365d" },
   { "name": "sampling", "query": "1m,10m,30m,1h,6h,12h,1d,1w" }
  ]
 },
 "panels": [
  { "title": "Lifetime Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"StepCount\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Flights climbed",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"FlightsClimbed\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Distance walked ($tag_unit)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"DistanceWalkingRunning\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Distance cycled ($tag_unit)",
     "measurement": "DistanceCycling",
     "query": "SELECT sum(\"value\") FROM \"DistanceCycling\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hours standing",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\")/60 FROM \"AppleStandTime\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hours exercising",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\")/60 FROM \"AppleExerciseTime\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hours functional strength training",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"FunctionalStrengthTraining\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "Hours cycling",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"Cycling\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "Hours running",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"Running\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "Hours playing squash",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"Squash\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "Hours skiing",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"DownhillSkiing\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "alias": "Hours yoga",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "query": "SELECT sum(\"value\")/60 FROM \"Yoga\" WHERE (\"device\" =~ /^$source$/) AND $timeFilter GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  { "title": "Periodic Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workout duration ($period)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FunctionalStrengthTraining",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cycling",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Running",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Squash",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Swimming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Yoga",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Hiking",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Climbing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DownhillSkiing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Slopes" }
     ]
    }
   ]
  },
  {
   "title": "Distance walked ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DistanceWalkingRunning",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "Distance cycled ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DistanceCycling",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minutes of exercise ($period)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StepCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "Flights climbed ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "flights" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FlightsClimbed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy burned ($period)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "alias": "Active Energy",
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ActiveEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Basal Energy",
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BasalEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time spent standing ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleStandTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average walking speed ($period)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$period" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Health Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Body mass ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lbs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" }
     ],
     "measurement": "BodyMass",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" }
     ],
     "measurement": "LeanBodyMass",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cardio fitness ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "VO2Max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate variability ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRateVariabilitySDNN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate statistics ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Maximum heart rate",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Minimum heart rate",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Average heart rate",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Walking/Resting heart rate ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Walking heart rate",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingHeartRateAverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Resting heart rate",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RestingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Respiratory rate ($sampling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RespiratoryRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}