name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - k0rventen
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following informations, that will help me greatly when reproducing your issue. Thanks !


  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      value: "A bug happened!"
    validations:
      required: true


  - type: input
    id: env 
    attributes:
      label: Environment 
      description: What is your OS / machine type ? 
      placeholder: ex. Ubuntu 23.04, macOS with Apple Silicon, Windows with WSL or Docker Desktop
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant logs from the ingester container
      render: shell
    validations:
      required: true


  - type: textarea
    id: compose
    attributes:
      label: docker-compose.yml
      description: Please copy and paste the content of your docker-compose.yml file
      render: shell
    validations:
      required: true
